services:
  auth:
    build:
      context: ./auth-service
    security_opt:
      - seccomp=unconfined

  users:
    build:
      context: ./user-service
    security_opt:
      - seccomp=unconfined

  chat:
    build:
      context: ./chat-service
    security_opt:
      - seccomp=unconfined

  wall:
    build:
      context: ./wall-service
    security_opt:
      - seccomp=unconfined
